[package]
name = "yew-practice"
version = "0.1.0"
authors = ["wasanx25 <wasanx25@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
serde = "1"
serde_derive = "1"
yew = "0.17"
wasm-bindgen = "0.2"
